Framework:
  Order: 4
  PDE: Harm
  Train:
    batch_size: 1024
    epochs: 1000
    device: cuda
    optimizer: 
      type: Adamax
      lr: 1e-3
    lr_scheduler:
        name: MultiStepLR
        milestones: [2000,5000]
        gamma: 0.2
    eval: 10
  Preprocess:
    normal_min: none
    normal_max: none
  Network:
    input: 1
    hidden: 64
    output: 1
    layer: 5
    act: Sine
    output_act: False
    pretrained: none
Log: 
  outputs_dir: outputs
  project_name: Harmonic
  stdlog: false
  tensorboard: true